package com.example.onlinecourierservices.utils;

public interface MessageConstants {

    String USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
    String EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String EMAIL_PATTERN = "EMAIL_PATTERN";
    String BAD_REQUEST = "BAD_REQUEST";
    String VERIFY_BY_EMAIL = "VERIFY_BY_EMAIL";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String VERIFY_BY_PHONE_NUMBER = "VERIFY_BY_PHONE_NUMBER";
    String PASSWORD_SUCCESSFULLY_CHANGED = "PASSWORD_SUCCESSFULLY_CHANGED";
    String PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL = "PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL";
    String VERIFICATION_CODE_SENT_TO_PHONE_NUMBER = "VERIFICATION_CODE_SENT_TO_PHONE_NUMBER";
    String VERIFICATION_CODE_SENT_TO_EMAIL = "VERIFICATION_CODE_SENT_TO_EMAIL";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String PASSWORD_CAN_NOT_BE_EMPTY = "PASSWORD_CAN_NOT_BE_EMPTY";
    String PASSWORD_ERROR = "PASSWORD_ERROR";
    String ADMIN_ROLE_CAN_NOT_BE_DELETED = "ADMIN_ROLE_CAN_NOT_BE_DELETED";
    String PHONE_NUMBER_CAN_NOT_BE_EMPTY = "PHONE_NUMBER_CAN_NOT_BE_EMPTY";
    String PHONE_NUMBER_SHOULD_MATCH_REGEX = "PHONE_NUMBER_SHOULD_MATCH_REGEX";
    String PASSWORD_SHOULD_MATCH_REGEX = "PASSWORD_SHOULD_MATCH_REGEX";
    String YOU_DO_NOT_HAVE_PERMISSION = "YOU_DO_NOT_HAVE_PERMISSION";

    String MANY_SMS_CODE_SENT = "MANY_SMS_CODE_SENT";
    String SMS_CODE_EXPIRED = "SMS_CODE_EXPIRED";
    String SMS_CODE_ALREADY_USED = "SMS_CODE_ALREADY_USED";
    String SUCCESSFULLY_SMS_SENT = "SUCCESSFULLY_SMS_SENT";
    String USER_PERMISSION_RESTRICTION = "USER_PERMISSION_RESTRICTION";
    String TOKEN_NOT_VALID = "TOKEN_NOT_VALID";
    String REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED";
    String WRONG_ACCESS_TOKEN = "WRONG_ACCESS_TOKEN";
    String ACCESS_TOKEN_NOT_EXPIRED = "ACCESS_TOKEN_NOT_EXPIRED";
    String SMS_CODE_MUST_NOT_BE_NULL = "SMS_CODE_MUST_NOT_BE_NULL";
    String DO_NOT_HAVE_PERMISSION_TO_USE_THIS_WAY = "DO_NOT_HAVE_PERMISSION_TO_USE_THIS_WAY";
    String PAGE_NOT_FOUND = "PAGE_NOT_FOUND";
    String METHOD_ERROR = "METHOD_ERROR";
    String UNACCEPTABLE = "UNACCEPTABLE";
    String SMS_CODE_ID_CAN_NOT_BE_NULL = "SMS_CODE_ID_CAN_NOT_BE_NULL";
    String SET_USER_PRINCIPAL_IF_ALL_OK_METHOD_ERROR = "Error in JwtAuthenticationFilter setUserPrincipalIfAllOk method: ";
    String EMAIL_CAN_NOT_BE_EMPTY = "EMAIL_CAN_NOT_BE_EMPTY";
    String  FIRST_NAME_CAN_NOT_BE_EMPTY = "FIRST_NAME_CAN_NOT_BE_EMPTY";
    String LAST_NAME_CAN_NOT_BE_EMPTY = "LAST_NAME_CAN_NOT_BE_EMPTY";
    String EMAIL_SHOULD_MATCH_REGEX = "EMAIL_SHOULD_MATCH_REGEX";
    String PRE_PASSWORD_CAN_NOT_BE_EMPTY = "PRE_PASSWORD_CAN_NOT_BE_EMPTY";
    String PRE_PASSWORD_SHOULD_MATCH_REGEX = "PRE_PASSWORD_SHOULD_MATCH_REGEX";
    String LINK_SENT_FOR_FORGOT_PASSWORD = "LINK SENT FOR FORGOT PASSWORD";
    String ACCOUNT_CREATED = "ACCOUNT CREATED";
    String VERIFIED = "VERIFIED";
    String VERIFICATION_CODE_INCORRECT_OR_USED = "VERIFICATION CODE INCORRECT OR USED";
    String LOGOUT = "LOGOUT";

    String SEARCHED_BY_ANYTHING = "SEARCHED BY ANYTHING";
    String COMPANY_NOT_FOUND = "COMPANY NOT FOUND";
    String EMAIL_SENDING_ERROR = "EMAIL SENDING ERROR";
    String TOKEN_TYPE = "Bearer ";
    String CATEGORY_ALREADY_CREATE = "Category already create";
    String CATEGORY_SUCCESSFULLY_CREATE = "Category successfully create";
    String CATEGORY_NOT_FOUND = "Category not found";
    String CATEGORY_SUCCESSFULLY_UPDATE = "Category successfully update";
}
